# Generated by Django 5.0.1 on 2024-01-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='working',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
