# Generated by Django 5.0.1 on 2024-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todoitem_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
